[package]
name = "rs-unicode-string"
version = "0.1.0"
edition = "2021"
authors = [
    "Tomasz Mikus <mikus.tomasz@gmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
