[package]
name = "u32_string_tests"
version = "0.1.0"
edition = "2021"
authors = [
    "Tomasz Mikus <mikus.tomasz@gmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
u32_string = { path = "../u32_string" }
